### ISSUE TITLE
No compatibility with Symfony 4.4/5

### ISSUE THREAD

**Issue by Bensemer** [Alexandre-T/casguard#9]
The current version is not compatible with Symfony 4.4 / 5.

**Comment by Alexandre-T** [comment]
Not yet, but feel free to contribute! :)

**Comment by Mick3DIY** [comment]
Bonjour Alexandre,

concernant les tests unitaires, juste une petite modification dans DependencyInjection /Configuration.php:

`...
$treeBuilder
->getRootNode()
     ->children()
...`

au lieu de : 

`...
$rootNode = $treeBuilder->root('cas_guard');
        $rootNode
            ->children()
...`

C'est à partir de Symfony 4.3 : Treebuilder->root() @deprecated since Symfony 4.3, pass the root name to the constructor instead.

Sinon tout va bien ;)

**Comment by Alexandre-T** [comment]
Bonjour, 

Je viens de faire cette mise à jour dans un autre bundle. Il ne suffit pas de changer, car on brise la compatibilité avec les versions antérieures. J'ai donc rajouté un test. En raison du covid-19, je suis mobilisé par mon emploi. Je vais essayer de le reproduire sur ce bundle d'ici la fin du mois.

**Comment by Mick3DIY** [comment]
Effectivement pour les versions anciennes, j'avais oublié... Tous en V4 ! :)
Sinon bon courage et confinement à tous. @Alexandre-T

**Comment by Alexandre-T** [comment]
Fixed in [version 1.0.2](https://github.com/Alexandre-T/casguard/releases/tag/1.0.2)
